---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bggdb
  template:
    metadata:
      name: bggdb-pod
      namespace: bggns
      labels:
        name: bggdb
    spec:
      containers:
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: db-port
          containerPort: 3306
        livenessProbe:
          exec:
            command: ['mysqladmin', 'ping']
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    name: bggdb
  ports:
  - port: 3306
    targetPort: db-port
