---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovdeploy 
  namespace: myns
  labels:
    apps: dov
    name: dov-deploy
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      dept: eng
      commit: abc123
  template:
    metadata:
      name: mypod
      namespace: myns
      labels:
        app: myapp
        dept: eng
        commit: abc123
    spec:
      containers:
      - name: mypod-container
        image: ezekieltoh/cfdsa-task1:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: app-port
          containerPort: 3000
        env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['pod-template-hash']


---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: myns  
  labels:
    app: dov
    name: dov-svc
spec:
  type: ClusterIP
  selector:
    app: myapp
    dept: eng
    commit: abc123
  ports:
  - port: 8000
    targetPort: app-port







      

